require(knitr)
require(markdown)
# setwd("~/GitHub repositories/GettingAndCleaningData/Project")
setwd("~/Documents/R Project/GettingAndCleaningData/GettingAndCleaningData")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")